### ISSUE TITLE
build-failing

### ISSUE THREAD

**Issue by felixphool** [MuskKat/Simplii#3]
The current state of the project is experiencing a build failure, hindering the successful compilation and deployment of the project. This issue needs urgent attention to ensure the project's continued development and stability.

**Comment by MuskKat** [comment]
Fixed gist secret https://github.com/MuskKat/Simplii/commit/35cf01d1cb1d6ea34b8eb43ebc034ee310d7d75b

**Comment by MuskKat** [comment]
+ fixed Unit Testing
